# -*- coding: utf-8 -*-
"""Pandas_27-06-2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWovPfx9XLXo2WUuz8t7akAPnl3fmyT-
"""

import pandas as pd
print(pd.__version__)

a=[105,101,203]
s=pd.Series(a,index=["x","y","z"])
print(s)
print(s.sort_values())

import numpy as np
import pandas as pd
a=np.array([1,2,3])
b=pd.Series(a,index=["x","y","z"])
print(b)

import numpy as np
import pandas as pd
a=np.array([1,2,3])
b=pd.Series(a,index=["x","y","z"])
print(b.index)
print(b.size)
print(b.head(2))
print(b.tail(1))

import pandas as pd
d=pd.read_csv("restaurant_data.csv")
print(d)

import pandas as pd
d=pd.read_csv("restaurant_data.csv")
df=pd.DataFrame(d)
print(df)

import pandas as pd
data1 = {
    "Customer ID": ["C-26247", "C-35067", "C-34590", "C-16668", "C-12196", "C-2600", "C-9047", "C-2206", "C-25607", "C-11606"],
    "Name": ["Tandra Olszewski", "Jeannette Cha", "Keva Godfrey", "Elva Sackett", "Sade Constable", "Gina Weir", "Lacey Cybulski", "Karrie Dickison",
             "Tona Wigington", "Hellen Alexis"],
    "Gender": ["F", "F", "F", "M", "F", "F", "M", "M", "M", "F"],
    "Age": [47, 57, 52, 65, 60, 59, 43, 65, 64, 27],
    "Income (USD)": [3472.69, 1184.84, 1266.27, 1369.72, 1939.23, 2944.81, 1957.31, 1403.63, 1604.65, 949.17],
    "Income Stability": ["Low", "Low", "Low", "High", "High", "Low", "Low", "High", "Low", "Working"],
    "Profession": ["Commercial associate", "Working", "Working", "Pensioner", "Pensioner", "Working", "Working", "Pensioner", "Working", "Working"],
    "Type of Employment": ["Managers", "Sales staff", "", "", "", "Sales staff", "Sales staff", "", "", "Laborers"],
    "Location": ["Semi-Urban", "Rural", "Semi-Urban", "Rural", "Urban", "Semi-Urban", "Rural", "Semi-Urban", "Semi-Urban", "Rural"],
    "Loan Amount Request (USD)": [137088.98, 104771.59, 176684.91, 97009.18, 109980, 31465.78, 150334.11, 121029.27, 39475.31, 24703.89]
}
d=pd.DataFrame(data1)
print(d)

import pandas as pd
s=["Location","Cuisine","Rating"]
d=pd.read_csv("restaurant_data.csv",usecols=s)
print(d.head(3))

import pandas as pd
d=pd.read_csv("restaurant_data.csv")
df=pd.DataFrame(d)
#print(df.info())
#print(df.describe())
#print(df.isnull().sum())
#print(df.columns)
print(df.dtypes)

import pandas as pd
d=pd.read_csv("restaurant_data.csv")
df=pd.DataFrame(d)
#print(df["Cuisine"].value_counts())
#print(df["Cuisine"].unique())